회비 회원 추가
ubuntu-kr/ubucon-kr-2023 pull request #10
Opened 2023-07-23 07:16 UTC by lego37yoon

다음과 같은 변경 사항을 추가했습니다.

- 개인 후원자 명단에 회비 회원 참여자도 같이 기록하도록 번역문 / 글 내용 / JSON 파일이 변경되었습니다.
- 세션 다운로드에 실패한 경우에는 JSON 파싱 오류 대신 세션에만 오류가 발생했다는 내용을 표시할 수 있도록 변경했습니다.
- 영문 페이지의 하단 푸터를 번역하였습니다.

다만, 현재 **회비 회원 참여자 명단**이 없어 반영하지 않은 관계로, 이대로 머지하시게 되면 회비 참여자는 0명, 카드는 표시되지 않게 됩니다. 따라서 머지 후에는 빠른 최신화가 필요할 것 같습니다.

2023-07-25 03:40 UTC, sukso96100 commented
회비 회원 영문 표기가 좀 애매하군요. Members with dues 같은 형태로 수정 해 주심 좋을 것 같습니다.

2023-07-25 03:54 UTC, lego37yoon commented
어떻게 표현하면 좋을지 몰라 고민하다가 작성하였는데, 더 나은 표기 알려주셔서 감사합니다. 이번에 후원사 목록 올릴 때 이 PR에 함께 수정하겠습니다.

2023-07-25 11:42 UTC, lego37yoon commented
추가로 다음과 같이 진행하였습니다.

### 스폰서 추가

| 구분 | 이름 |
| --- | --- |
| Government Partner | NIPA |
| Diamond Sponsor | Ubuntu |
| Silver Sponsor | CloudMate |

### 회비 회원 추가 관련

- 영문 표기 메뉴: Community Members -> Members with dues
- 본문: Ubuntu Korea Community Members -> Ubuntu Korea Community Members with dues

회비 회원 목록은 전달받는대로 이 PR에 같이 포함하도록 하겠습니다.

2023-07-25 12:18 UTC, lego37yoon commented
알려진 문제를 해결하고, 추가로 공개된 연사자 분들의 사진이 정상적으로 표시될 수 있도록 개선했습니다.

2023-07-26 12:36 UTC, sukso96100 requested changes
- 후원사 순서를 Diamond - 장소 - 정부 - 골드 - 실버 - 브론즈 - 서포터 순으로 부탁드립니다.
- 회비 후원 설명 텍스트에 약간의 오탈자가 보이네요.

2023-07-26 12:38 UTC, lego37yoon commented
오탈자가 있었군요 한 번 더 확인해보겠습니다.
순서 같이 조정해서 커밋 추가하겠습니다.

2023-07-26 12:57 UTC, sukso96100 commented
추가로 CloudMate -> Cloudmate 로 해 주시면 되겠습니다.

2023-07-26 13:34 UTC, lego37yoon commented
수정하였습니다. 한 번 더 확인해주시면 감사하겠습니다.

2023-07-26 13:48 UTC, sukso96100 approved these changes

2023-07-26 13:48 UTC, merged